# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch: [01-blinky, 01-blinky]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      # We use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Init Arduino config
        run: arduino-cli config init --additional-urls https://dl.espressif.com/dl/package_esp32_index.json

      - name: Install platform
        run: arduino-cli core update-index

      - name: Add core
        run: arduino-cli core install esp32:esp32

      - name: Compile ${{matrix.sketch}}
        run: arduino-cli compile --fqbn esp32:esp32:esp32 ./src/${{matrix.sketch}}